site_name: Spotify to YouTube Music Transfer
site_description: Transfer your Spotify playlists to YouTube Music with ease
site_author: bewithdhanu
site_url: https://bewithdhanu.github.io/spotify-to-youtube-music/

repo_name: bewithdhanu/spotify-to-youtube-music
repo_url: https://github.com/bewithdhanu/spotify-to-youtube-music
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage Examples: usage-examples.md
  - Documentation:
    - API Reference: api.md
    - Architecture: architecture.md
  - Help:
    - Troubleshooting: troubleshooting.md

plugins:
  - search:
      lang: en

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bewithdhanu/spotify-to-youtube-music
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spotify-youtube-transfer/
  version:
    provider: mike

copyright: Copyright &copy; 2024 bewithdhanu - MIT License