site_name: Spotify to YouTube Music Transfer
site_description: Transfer your Spotify playlists to YouTube Music with ease
site_author: bewithdhanu
site_url: https://bewithdhanu.github.io/spotify-to-youtube-music/

repo_name: bewithdhanu/spotify-to-youtube-music
repo_url: https://github.com/bewithdhanu/spotify-to-youtube-music
edit_uri: edit/main/docs/

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - fenced_code

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage Examples: usage-examples.md
  - Documentation:
    - API Reference: api.md
    - Architecture: architecture.md
  - Help:
    - Troubleshooting: troubleshooting.md

plugins:
  - search:
      lang: en

extra:
  version:
    provider: mike

copyright: Copyright &copy; 2024 bewithdhanu - MIT License